# Generated by Django 5.0.3 on 2024-09-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='timestamp',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
