# Generated by Django 5.0.3 on 2024-09-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_subtitle_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='timestamp',
        ),
    ]
